### ISSUE TITLE
workbench for nurbs

### ISSUE THREAD

**Issue by microelly2** [edwardvmills/NURBSlib_EVM#1]
hello,
are you interested in integrating  this lib into a freecad workbench?
I can support you on this way because I'm writing on a nurbs editor too and it's a good idea to bring the pieces sometime together.

**Comment by edwardvmills** [comment]
Hi Microelly, i'm glad you are showing interest. I like the idea of making a workbench, although i prefer gplv3 for the time being. Are you ok with a standalone workbench? 
 Right now a lot of useful functions have no icons, but the biggest concern is that i am about to rewrite everything with python features to make it parametric.

If you want non parametric "Part" type objects, the current version can be used.

Im at work right now, so ill tell you more later

**Comment by microelly2** [comment]
Nice to read your mail.
I think its useful to go the step to a workbench. whatever licence you 
want its not a problem for me if it is still open source and free usable.
I prefer loose couplings as long as it follows the idea of open reusable 
software.

My idea is to make a workbench and bring some ordering into the lots of 
macros with menus and toolbars
The icons can come later(I'm not a great painter, so my icons are often 
handdrawn)
and then  your scripts can bew reworked and become parametric.

Am 25.07.2016 um 17:40 schrieb edwardvmills:

**Comment by edwardvmills** [comment]
Hi Microelly. I intended to follow up yesterday, but i may not have time until the weekend. Not ignoring :) just busy with work. Do you have nurbs stuff already in one of your repos? Do you have specific ideas about how to organize the workbench?

**Comment by microelly2** [comment]
First step:
create a workbench and add all of your functions which have already 
icons to some toolbars.

my work on nurbs:
https://github.com/microelly2/reconstruction
see:
reconstruction/nurbs.py
reconstruction/nurbs_dialog.py
and
examples/example_nurbs*

https://www.youtube.com/watch?v=xY7o6rBQP1M
https://www.youtube.com/watch?v=AE0j9PErfHY
https://www.youtube.com/watch?v=e9_dBCfcZnM
https://www.youtube.com/watch?v=j-vcTKNb-B8
https://www.youtube.com/watch?v=11cthiBCfFg

at the moment I work on segmentation and recombination of nurbs,
my idea: working on a large nurbs is going theses steps:
segment it into smaller parts
rework such a small area with less then 36 poles
put then all together to the big nurbs.

Am 27.07.2016 um 03:34 schrieb edwardvmills:

**Comment by edwardvmills** [comment]
I could really use some help developing the parametric and object oriented aspects of the code. From looking at your videos, i clearly see you have a better command of these areas than i do. 

The following is based on what i understand of your tools after watching the videos. If it is not correct, please tell me more about your strategy.

Although i haven't published a workbench, i do have very specific goals in mind for the workflow. I am trying to figure out how to blend your set of tools with mine and i am not sure how to do it. It is hard to get clear communication sometimes over email and message boards. Do you want to merge our code structures, place the tools as they are side by side in a workbench, or are you offering to help me accomplish my goals :) ?

I think there is something we definitely should collaborate on:
-a compatible parametric nurbs object that shows up consistently in the design tree.

-NURBS_object
-->Pole_structure

my functions and yours would always produce objects of this type, and your functions could always modify my objects.

This is already true if we go down to the FreeCAD shape level, but not in a very meaningful way. We can get the poles, but we lose all information about how the poles relate to each other. In my objects, there are very few poles, but they are completely determined (for smoothness across joints).

here is the basic architecture i plan to use:
-sketches, as provided by FreeCAD
-polylines (curve poles in sequence), parametrically linked to the sketches (or derived from isolines of existing surfaces / segments of existing curves)
-grids (surface poles in correct UV sequence), parametrically linked to the polylines
-NURBS curves, parametrically linked to the polylines
-NURBS surfaces, parametrically linked to the grids (or segments of existing surfaces)

the model tree would look like this (fully expanded):
sketch1
sketch2
sketch3
sketch4

poly1
-->sketch1
poly2
-->sketch2
poly3
-->sketch3
poly3
-->sketch3

curve1
-->poly1
----->sketch1
curve2
-->poly2
----->sketch2
curve3
-->poly3
----->sketch3
curve4
-->poly4
----->sketch4

surface1
-->curve1
----->poly1
-------->sketch1
-->curve2
----->poly2
-------->sketch2
-->curve3
----->poly3
-------->sketch3
-->curve4
----->poly4
-------->sketch4

The polylines are completely defined by the sketches.
The grid function uses a completely defined method to position the inner poles (and calculate the correct weight) based on the edge polygons.

My goal is for the NURBS surface to be FULLY defined by the sketches. Once this is true and works properly, your tools that allow refining the inside of the NURBS would be very handy for me as well. It would be used as a way to add detail.

if we can agree on the object structure for
-polyline
-grid
-curve
-surface
then we can each write our own methods to produce the polylines and grids, and use the exact same curve and surface objects.

if i can easily pull the first 2 or 3 rows of poles starting from the edge of one of your surfaces, i can generate a surface that flows from your edge with G1, G2 or G3 quality.

DOes this sound like something you'd like to work on with me?

**Comment by microelly2** [comment]
Am 30.07.2016 um 20:20 schrieb edwardvmills:

> I could really use some help developing the parametric and object 
> oriented aspects of the code. From looking at your videos, i clearly 
> see you have a better command of these areas than i do.
> 
> The following is based on what i understand of your tools after 
> watching the videos. If it is not correct, please tell me more about 
> your strategy.
> 
> Although i haven't published a workbench, i do have very specific 
> goals in mind for the workflow. I am trying to figure out how to blend 
> your set of tools with mine and i am not sure how to do it. It is hard 
> to get clear communication sometimes over email and message boards. Do 
> you want to merge our code structures, place the tools as they are 
> side by side in a workbench, or are you offering to help me accomplish 
> my goals :) ?

what we need:

(1) methods to connect nurbs on their borders to get closed shells and 
at the end solids
this can be done with your methods (if the borders can be back 
transformed to sketches (what sometime will be possible))

(2) methods to interpolate/approximate points sets by nurbs
there are already good methods inside OCC, SciPy to achieve this

(3) methods to change nurbs by modifying knots, poles, weights
where I started to work

(4) a Gui that is useable by non-programmers - in FreeCAD words: a 
workbench with dialogs, toolbars and so on

the common datastructure of the bspine/nurbs is the base of our work

we have to find ways how designer can change pole/knot/wheights on an 
intuitive way without programming knowledge
that means realtime visualization of changes, 2D/3D editors for  the 
datasets

So we can go the same way.

**Comment by edwardvmills** [comment]
for (1), i use the Part workbench directly

my intention for my workbench is to have my tools, and to simply include:
-all sketch toolbars
-extrude, revolve, mirror, thickness, etc from Part (not PartDesign)

Right now i'm on the edge of major rewrite.
i have made a few test classes. they do sketch>controlpolyline>curve correctly linked.
they are in the file para_NURBS. This file is just a test area.

i just made my rewrite plan:
[deleted because of horrible formatting python > markup]

you can read about it in NURBSLib_EVM.py, starting around line 1132

this will make almost all the existing GUI macros obsolete :(  but it's worth it!
I went in this direction because rebuilding the models by hand after each change was starting to slow me down too much.

**Comment by edwardvmills** [comment]
lol, did not intend my python comment tags to be interpreted as markup

**Comment by microelly2** [comment]
I have created a new project 
https://github.com/microelly2/freecad-nurbs
you should get a notification to participate
my idea is to merge step by step our methods.
at the moment there is a generic workbench with only my nurbs generator action.
I will move my methods step by step from reconstruction workbench  to this
you can try to add your actions too and then I do the first update steps  the gui for the wb .

**Comment by edwardvmills** [comment]
Hi Microelly. I took a look at your repo, but i'm not sure i understand your modeling strategy. Have you read the project statement on my tools? i have something very specific in mind for my tools. I understand the concept of reconstruction, but that is very far from my own goals right now.

Also, i'm sorry, but i have no desire to make anything of mine lgpl at this time. My macros and library are free for people to use, but as gpl3 (full strength gpl). Please understand, this is just a library of macros _right now_, but i have a full workflow planned. If our tools are compatible, that is great, but i need to focus on the core functionality of my workflow.

This is part of the reason why i don't have an actual workbench right now. my system is not ready for end users. I can't convince people to do things my way if my way doesn't work yet. sorry

**Comment by luzpaz** [comment]
What's the status of this becoming a Workbench?

**Comment by edwardvmills** [comment]
Hi! i have created a new repo for the workbench. I think i will be ready to open it within a month. I can't tell how useful it will be to others, since the project has a long distance goal.
The workbench i have in mind right now will simply provide a GUI to the base classes of the library. It _can_ be used to model, but so far no one has used it to design anything. One person did follow the tutorials.

**Comment by tplaiho** [comment]
I am very interested of your tool. So far I do not understand it truly well, but I will follow the tutorials first. I may later make some questions...however do you think that I can model a car with class A surfaces with your methods and tools? I would like to try that, I have been able to do cars with Class A surfaces with Catia and Autodesk Alias tools and also with Rhine, but these are traditional tools and your approach is very different.

**Comment by edwardvmills** [comment]
Please see the link to the 'silk' repo. It's where all future work will go.

Class A automotive quality stuff. Not yet, but that is the goal. FreeCAD has high quality sweeps and lofts already, just not full options ( rails, G3, etc).

I welcome experienced surface modelers to try it, but beware, future Dev may break current models

**Comment by edwardvmills** [comment]
https://edwardvmills.github.io/Silk/

Is the workbench that takes over this project.

**Comment by tplaiho** [comment]
Thank you. I have installed SILK to my FreeCAD 0.17. I am using Centos 7 OS. Very good. In the following days I will take a closer look of your tutorials. They are very important in order to understand your tool. I am planning also to do some architecture with your Silk tool and I think it is already good enough for this kind of purpose. That is because architecture cannot be typically too organic by its nature due to costs and possibility to manufacture. If a car with class A continuity is not yet possible I may do something else what is possible. Stay tuned in the following weeks some new design may appear.  You are making important work for FreeCAD, I can see that already.
